"""Global constants shared across ACF modules."""

JSON_SCHEMA_VERSION = 1

EXIT_CHECK_FAILED = 1
EXIT_INPUT_ERROR = 2
EXIT_SAFETY_REFUSED = 3
EXIT_RUNTIME_ERROR = 70

TARGET_EXISTS_APPEND_REQUIRED = "TARGET_EXISTS_APPEND_REQUIRED"
APPEND_FORCE_CONFLICT = "APPEND_FORCE_CONFLICT"
ANCHOR_NOT_FOUND = "ANCHOR_NOT_FOUND"
